locals {
  name = "order-service-${var.environment}"
}

# ADR-0005: Multi-AZ VPC with public/private/isolated subnets across 3 AZs.
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.13"

  name = "${local.name}-vpc"
  cidr = var.vpc_cidr
  azs  = var.azs

  public_subnets  = [for i, _ in var.azs : cidrsubnet(var.vpc_cidr, 4, i)]     # /20
  private_subnets = [for i, _ in var.azs : cidrsubnet(var.vpc_cidr, 4, i + 4)] # /20
  intra_subnets   = [for i, _ in var.azs : cidrsubnet(var.vpc_cidr, 4, i + 8)] # /20  (isolated for DB)

  enable_nat_gateway      = true
  single_nat_gateway      = true # cost-tradeoff per design §6.1 (NAT egress)
  enable_dns_hostnames    = true
  map_public_ip_on_launch = false
}

# ADR-0001: ECS Fargate cluster.
module "ecs_cluster" {
  source  = "terraform-aws-modules/ecs/aws//modules/cluster"
  version = "~> 5.12"

  cluster_name = "${local.name}-cluster"

  fargate_capacity_providers = {
    FARGATE = {
      default_capacity_provider_strategy = { weight = 70 }
    }
    FARGATE_SPOT = {
      default_capacity_provider_strategy = { weight = 30 } # ADR-0001 cost note
    }
  }
}

# ALB (design §6.1 edge for api-gateway-svc).
module "alb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "~> 9.10"

  name    = "${local.name}-alb"
  vpc_id  = module.vpc.vpc_id
  subnets = module.vpc.public_subnets

  security_group_ingress_rules = {
    https = {
      from_port   = 443
      to_port     = 443
      ip_protocol = "tcp"
      cidr_ipv4   = "0.0.0.0/0"
    }
  }
  security_group_egress_rules = {
    all = { ip_protocol = "-1", cidr_ipv4 = "0.0.0.0/0" }
  }

  listeners = {
    http_redirect = {
      port     = 80
      protocol = "HTTP"
      redirect = { port = "443", protocol = "HTTPS", status_code = "HTTP_301" }
    }
    # NOTE: TLS listener requires an ACM cert ARN — out of scope for IaC pass.
    # User must add `https` listener referencing certificate_arn after issuing ACM cert.
  }
}

# ADR-0001: api-gateway-svc as ECS service.
module "api_service" {
  source  = "terraform-aws-modules/ecs/aws//modules/service"
  version = "~> 5.12"

  name        = "${local.name}-api"
  cluster_arn = module.ecs_cluster.arn

  cpu    = 512
  memory = 1024

  container_definitions = {
    api = {
      image     = var.api_image
      essential = true
      port_mappings = [{
        containerPort = 8080
        hostPort      = 8080
        protocol      = "tcp"
      }]
      environment = [
        { name = "AWS_REGION", value = var.region },
        { name = "DB_SECRET_ARN", value = aws_secretsmanager_secret.db_password.arn },
        { name = "COGNITO_USER_POOL_ID", value = aws_cognito_user_pool.sellers.id },
      ]
      readonly_root_filesystem = true
    }
  }

  desired_count = var.api_desired_count
  subnet_ids    = module.vpc.private_subnets

  load_balancer = {
    service = {
      target_group_arn = "PLACEHOLDER" # wire up after ACM cert + listener created
      container_name   = "api"
      container_port   = 8080
    }
  }

  # NOTE: channel adapters (naver/coupang/ownsite), order-ingest, notification-worker
  # are the same pattern — duplicate this module call per ADR-0003 once images exist.
}

# ADR-0004: Cognito User Pool for seller authentication.
resource "aws_cognito_user_pool" "sellers" {
  name = "${local.name}-sellers"

  password_policy {
    minimum_length    = 12
    require_lowercase = true
    require_uppercase = true
    require_numbers   = true
    require_symbols   = true
  }

  mfa_configuration = "OPTIONAL"
  software_token_mfa_configuration { enabled = true }

  schema {
    name                = "role"
    attribute_data_type = "String"
    mutable             = true
    string_attribute_constraints {
      min_length = 1
      max_length = 32
    }
  }

  account_recovery_setting {
    recovery_mechanism {
      name     = "verified_email"
      priority = 1
    }
  }
}

resource "aws_cognito_user_pool_client" "web" {
  name         = "${local.name}-web"
  user_pool_id = aws_cognito_user_pool.sellers.id

  allowed_oauth_flows                  = ["code"]
  allowed_oauth_scopes                 = ["openid", "email", "profile"]
  allowed_oauth_flows_user_pool_client = true
  supported_identity_providers         = ["COGNITO"]
  callback_urls                        = ["https://EXAMPLE_app.example.com/auth/callback"]
  generate_secret                      = false
}

# Secrets Manager — DB master password generated by Terraform; rotated separately.
resource "aws_secretsmanager_secret" "db_password" {
  name = "${local.name}/aurora/master"
  # NOTE: rotation_lambda_arn not configured — set up rotation per K-ISMS.
}

# KMS CMK for S3 export bucket (PII per §3.6).
resource "aws_kms_key" "exports" {
  description             = "KMS for order-service S3 exports"
  enable_key_rotation     = true
  deletion_window_in_days = 30
}

resource "aws_s3_bucket" "exports" {
  bucket = "${local.name}-exports-EXAMPLE" # bucket names global; user must override
}

resource "aws_s3_bucket_server_side_encryption_configuration" "exports" {
  bucket = aws_s3_bucket.exports.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = aws_kms_key.exports.arn
    }
  }
}

resource "aws_s3_bucket_public_access_block" "exports" {
  bucket                  = aws_s3_bucket.exports.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
